[project]
name = "submitproject"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Mahan", email = "222mahan666@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "customtkinter>=6.0.0",
    "openai>=3.8.0",
]

[project.scripts]
app = "todo_app.login:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "todo_app"

[[tool.uv.index]]
url = "https://mirrors.ustc.edu.cn/pypi/simple"
default = true

[dependency-groups]
dev = [
    "pyinstaller>=6.22.2",
]
